package org.knowledge4retail.portalbackend

import org.knowledge4retail.portalbackend.domain.K4RStore
import org.knowledge4retail.portalbackend.infrastructure.dtapi.models.V0StoreAggregate

val k4rStoreListFixture = listOf(
    K4RStore(
        id = 123,
        storeName = "myRetailChain - de:1",
        storeNumber = "1",
        addressCountry = "DE",
        addressState = null,
        addressCity = null,
        addressPostcode = null,
        addressStreet = null,
        addressStreetNumber = null,
        addressAdditional = null,
        longitude = "null",
        latitude = "null",
        cadPlanId = null,
        externalReferenceId = null,
        shelfCount =99,
        shelfLayerCount =99,
        barcodeCount =99,
        productCount =99),
    K4RStore(
        id = 456,
        storeName = "myRetailChain - de:2",
        storeNumber = "2",
        addressCountry = "DE",
        addressState = "Schleswig Holstein",
        addressCity = "Sylt",
        addressPostcode = "25980",
        addressStreet = "Gaadt",
        addressStreetNumber = "33",
        addressAdditional = "Aquarium",
        longitude = "8.298439",
        latitude = "54.900944",
        cadPlanId = null,
        externalReferenceId = null,
        shelfCount =0,
        shelfLayerCount =0,
        barcodeCount =0,
        productCount =0),
    K4RStore(
        id = 678,
        storeName = "myRetailChain - de:3",
        storeNumber = "3",
        addressCountry = "DE",
        addressState = null,
        addressCity = "Bremen",
        addressPostcode = "28203",
        addressStreet = "Osterdeich",
        addressStreetNumber = "1",
        addressAdditional = null,
        longitude = "8.815281",
        latitude = "53.070467",
        cadPlanId = null,
        externalReferenceId = null,
        shelfCount =3000,
        shelfLayerCount =1000,
        barcodeCount =345,
        productCount =0),
)


val v0StoreAggregateListFixture = listOf(
    V0StoreAggregate(
        id = 123,
        storeName = "myRetailChain - de:1",
        storeNumber = "1",
        addressCountry = "DE",
        addressState = null,
        addressCity = null,
        addressPostcode = null,
        addressStreet = null,
        addressStreetNumber = null,
        addressAdditional = null,
        longitude = null,
        latitude = null,
        cadPlanId = null,
        externalReferenceId = null,
        shelfCount =99,
        shelfLayerCount =99,
        barcodeCount =99,
        productCount =99),
    V0StoreAggregate(
        id = 456,
        storeName = "myRetailChain - de:2",
        storeNumber = "2",
        addressCountry = "DE",
        addressState = "Schleswig Holstein",
        addressCity = "Sylt",
        addressPostcode = "25980",
        addressStreet = "Gaadt",
        addressStreetNumber = "33",
        addressAdditional = "Aquarium",
        longitude = 8.298439,
        latitude = 54.900944,
        cadPlanId = null,
        externalReferenceId = null,
        shelfCount =0,
        shelfLayerCount =0,
        barcodeCount =0,
        productCount =0),
    V0StoreAggregate(
        id = 678,
        storeName = "myRetailChain - de:3",
        storeNumber = "3",
        addressCountry = "DE",
        addressState = null,
        addressCity = "Bremen",
        addressPostcode = "28203",
        addressStreet = "Osterdeich",
        addressStreetNumber = "1",
        addressAdditional = null,
        longitude = 8.815281,
        latitude = 53.070467,
        cadPlanId = null,
        externalReferenceId = null,
        shelfCount =3000,
        shelfLayerCount =1000,
        barcodeCount =345,
        productCount =0),
)